tasks:
  - before: npm i -g firebase-tools rekit@next
vscode:
  extensions:
    - formulahendry.auto-complete-tag@0.1.0:XS3fJJUSAJ7NZnVWJBvrJQ==
    - toba.vsfire@1.4.1:h61hf1SYLs3VPHlSFosLlQ==
    - aaron-bond.better-comments@2.0.5:YKNfOclR4e8XAxlj4xp2AA==
    - jawandarajbir.react-vscode-extension-pack@0.4.0:Q9yUw5rorelmURZ8xJOeUw==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - eamodio.gitlens@9.9.3:4g0pgzmxBH0HkAs5mY8BWQ==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - MikeBovenlander.formate@1.1.2:F/8n957RNrijbA+7cD/o2Q==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - oderwat.indent-rainbow@7.4.0:nth8lnJRnQu9NcWvNc9KPA==